### ISSUE TITLE
report environment conflict.And which Python environment you are using ?

### ISSUE THREAD

**Issue by lijianfromearth** [hsp-iit/rl-icub-dexterous-manipulation#1]
Hello, I am trying to run your code to learn how it works. 
I'm curious about which Python environment you are using ？
because the setup.py file you provided has some conflicts.
------------------
install_requires=[
        'mujoco==2.3.0',
        'imitation==0.3.1',
        'dm_control==1.0.8',
        'stable-baselines3[extra]==1.5.0',
        'pyyaml',
        'torchvision',
        'pyquaternion',
        'clip @ git+https://github.com/openai/CLIP.git',
        'd3rlpy==1.1.1',
        'mvp @ git+https://github.com/ir413/mvp',
        'open3d',
        'vgn @ git+https://github.com/ethz-asl/vgn.git',
    ]
)
-----------------------------
imitation version 0.3.1 requires Python >=3.8.0, 
but d3rlpy version 1.1.1 can only run on Python 3.7.5, according to my tests.

**Comment by fedeceola** [comment]
Hi @lijianfromearth, thanks for your interest in our work!

I was using python 3.8.10. Please let me know if using this version solves the problem!

**Comment by lijianfromearth** [comment]
> Hi @lijianfromearth, thanks for your interest in our work!
> 
> I was using python 3.8.10. Please let me know if using this version solves the problem!

@fedeceola  Hi, I have been testing on Python 3.7.5 and 3.8.0. I found that d3rlpy can only be installed on Python 3.7.5, 
and Imitation can only be installed on Python versions 3.8.0 or higher.
 Additionally,this bug is when I  trying to install d3rlpy version 1.1.1 on Python 3.8.10 :

#####################################
pip install d3rlpy==1.1.1                                                                                                   ✭ ✱
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting d3rlpy==1.1.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3b/0c/bba8b546426819a2c297ddd9f2268b5f156180057e8db4a6b66eafa78e9b/d3rlpy-1.1.1.tar.gz (317 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      /home/yaxun/miniforge3/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-xz25edrj/d3rlpy_5db0312442fb4664b665c31a8ecee823/d3rlpy/dataset.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      from cython cimport view
      
      from cython.parallel import prange
      
      from dataset cimport CTransition
      ^
      ------------------------------------------------------------
      
      d3rlpy/dataset.pyx:15:0: 'dataset.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      from cython cimport view
      
      from cython.parallel import prange
      
      from dataset cimport CTransition
      ^
      ------------------------------------------------------------
      
      d3rlpy/dataset.pyx:15:0: 'dataset/CTransition.pxd' not found
      performance hint: d3rlpy/dataset.pyx:1053:5: Exception check on '_stack_frames' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_stack_frames' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_stack_frames' to allow an error code to be returned.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xz25edrj/d3rlpy_5db0312442fb4664b665c31a8ecee823/setup.py", line 23, in <module>
          ext_modules = cythonize([ext],
        File "/home/yaxun/miniforge3/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/home/yaxun/miniforge3/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: d3rlpy/dataset.pyx
      Compiling d3rlpy/dataset.pyx because it changed.
      [1/1] Cythonizing d3rlpy/dataset.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

please help me to use  d3rlpy.....

**Comment by fedeceola** [comment]
In the error in your comment you are using python 3.10. 

>  /home/yaxun/miniforge3/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-xz25edrj/d3rlpy_5db0312442fb4664b665c31a8ecee823/d3rlpy/dataset.pxd

Also, in my experiments, I wasn't using conda, but a python virtual environment. I run all my experiments on machines with ubuntu 20.04.

**Comment by fedeceola** [comment]
I just installed d3rlpy==1.1.1 in a brand new virtual environment and I didn't have any error.

**Comment by lijianfromearth** [comment]
> In the error in your comment you are using python 3.10.
> 
> > /home/yaxun/miniforge3/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-xz25edrj/d3rlpy_5db0312442fb4664b665c31a8ecee823/d3rlpy/dataset.pxd
> 
> Also, in my experiments, I wasn't using conda, but a python virtual environment. I run all my experiments on machines with ubuntu 20.04.

Thank you very mach.
Based on your hint, I found that the problem was with the Cython version. I reinstalled Cython 0.29.14, which resolved the issue.
Now the code can run, thank you.
I have another silly question: how do I enable rendering?
When I run the code, the training is running in the background, and there is none open simulator rendering.

python3 icub_visuomanip_drl.py --cfg configs/exp_resprect/resprect_mustard_superquadrics.yaml

I know this is a beginner's question, and I am also reading your code and learning gym. If you have time, please give me some tips, thank you.

**Comment by fedeceola** [comment]
You need to use the `--render_cameras` argument either from the command line or in the config file. There are quite a lot of arguments in the `icub_visuomanip_drl.py`, but there is a (hopefully clear enough) description of all of them in the code.

**Comment by lijianfromearth** [comment]
Thank you very mach.It is work.

> You need to use the `--render_cameras` argument either from the command line or in the config file. There are quite a lot of arguments in the `icub_visuomanip_drl.py`, but there is a (hopefully clear enough) description of all of them in the code.

**Comment by fedeceola** [comment]
Ok, great! Closing the issue!
