### ISSUE TITLE
When I add "camera" to observation_space ,I meet a error.

### ISSUE THREAD

**Issue by lijianfromearth** [hsp-iit/rl-icub-dexterous-manipulation#2]
error is :
exceptions.MemoryError:Unable to allocate 858. GiB for an array with shape (1000000, 3, 480, 640) and data type uinta

The error was caused by "set observation space." Do you know how I could modify it? ^v^

**Comment by fedeceola** [comment]
Hi @lijianfromearth, you are running out of memory. Training from images with that resolution and with that replay buffer size is quite impractical. If in your project you need to train a policy from raw images, I suggest to reduce replay buffer size and images resolution.
